// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyq-lCMMCfljSmMdEVsJD6SfOCX97gpI8',
    appId: '1:164488569422:web:a4d5de450b91f9b96e991f',
    messagingSenderId: '164488569422',
    projectId: 'astanovka-mobile-app',
    authDomain: 'astanovka-mobile-app.firebaseapp.com',
    storageBucket: 'astanovka-mobile-app.firebasestorage.app',
    measurementId: 'G-TEY1W485QP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQE4u_9xCOWLq9vQX_FOthL5MiN-fL7Jo',
    appId: '1:164488569422:android:017c31ff2f649f6b6e991f',
    messagingSenderId: '164488569422',
    projectId: 'astanovka-mobile-app',
    storageBucket: 'astanovka-mobile-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_hQgJFWoqHkY_YDB0kg-ZJTdz95iRBPY',
    appId: '1:164488569422:ios:ffc67c9d1de78d466e991f',
    messagingSenderId: '164488569422',
    projectId: 'astanovka-mobile-app',
    storageBucket: 'astanovka-mobile-app.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyq-lCMMCfljSmMdEVsJD6SfOCX97gpI8',
    appId: '1:164488569422:web:3bb0a45b19b9d7926e991f',
    messagingSenderId: '164488569422',
    projectId: 'astanovka-mobile-app',
    authDomain: 'astanovka-mobile-app.firebaseapp.com',
    storageBucket: 'astanovka-mobile-app.firebasestorage.app',
    measurementId: 'G-E6EKSJC5VX',
  );
}
